const constants = {
  MAX_TILES: 15
};

// Add action names
[
  "REQUEST_SCREENSHOT",
  "RECEIVE_SCREENSHOT",
  "REQUEST_SUGGESTED_DIRECTORY",
  "RECEIVE_SUGGESTED_DIRECTORY",
  "REQUEST_INIT",
  "RECEIVE_INIT",
  "RECEIVE_PREFS",
  "REQUEST_SEARCH_SUGGESTIONS",
  "RECEIVE_SEARCH_SUGGESTIONS",
  "UPDATE_SEARCH_STRING",
  "RECEIVE_REMOVE_SITE",
  "REQUEST_CURRENT_SEARCH_ENGINE",
  "RECEIVE_CURRENT_SEARCH_ENGINE",
  "REQUEST_VISIBLE_SEARCH_ENGINES",
  "RECEIVE_VISIBLE_SEARCH_ENGINES",
  "REQUEST_FRECENT",
  'RECEIVE_FRECENT',
  'REQUEST_INIT_USER_DATABASE',
  'REQUEST_INIT_USER_DATABASE_COMPLETE'
].forEach(action => constants[action] = action);

module.exports = constants;
