/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */
/*global self*/
/*exports mainSiteURLs*/

/**
 * THIS FILE IS AUTOMATICALLY GENERATED!
 * DO NOT MODIFY OR IT WILL JUST GET TRASHED.
 *
 * See: bin/generate-offline-files.js
 */
"use strict";
const mainSiteURLs = [ // jshint ignore:line
  "./",
  "sw.js",
  "css/contentSearchUI.css",
  "css/images/close.png",
  "css/images/controls.svg",
  "css/images/defaultFavicon.png",
  "css/images/history-icon.svg",
  "css/images/search-arrow-go.svg",
  "css/images/search-engine-placeholder.png",
  "css/images/search-indicator-magnifying-glass.svg",
  "css/images/shared-menu-check.svg",
  "css/images/whimsycorn.png",
  "css/newTab.css",
  "js/blockedLinks.js",
  "js/cells.js",
  "js/contentSearchUI.js",
  "js/customize.js",
  "js/drag.js",
  "js/dragDataHelper.js",
  "js/drop.js",
  "js/dropPreview.js",
  "js/dropTargetShim.js",
  "js/grid.js",
  "js/intro.js",
  "js/lib/async.js",
  "js/lib/cachetasks.js",
  "js/lib/swMessage.js",
  "js/mainSiteURLs.js",
  "js/newTab.js",
  "js/page.js",
  "js/pinnedLinks.js",
  "js/rectangle.js",
  "js/search.js",
  "js/sites.js",
  "js/transformations.js",
  "js/undo.js",
  "js/updater.js",
  "js/userDatabase.js",
  "locale/newTab.js",
].map(
  // Using URL API is very slow in workers because it does IPC.
  path => self.location.origin + "/" + path
);
